import pathlib
import sys
import unittest
from unittest.mock import MagicMock, patch

from PyQt5.QtGui import QCloseEvent, QIcon
from PyQt5.QtWidgets import QApplication, QStyle

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app_controller import AppController


class AppControllerTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def test_start_shows_tray_icon(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.tray_icon.show = MagicMock()

        started = controller.start()

        self.assertTrue(started)
        controller.tray_icon.show.assert_called_once()

    def test_build_icon_uses_standard_system_icon(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        icon = controller._build_icon()
        expected_icon = self.app.style().standardIcon(QStyle.SP_ComputerIcon)

        self.assertIsInstance(icon, QIcon)
        self.assertFalse(icon.isNull())
        self.assertFalse(expected_icon.isNull())
        self.assertFalse(icon.pixmap(16, 16).isNull())
        self.assertFalse(expected_icon.pixmap(16, 16).isNull())

    def test_start_shows_preview_window(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        started = controller.start()

        self.assertTrue(started)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertFalse(controller.preview_window.windowIcon().isNull())

    def test_preview_window_exposes_timer_control_buttons(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")

    def test_preview_window_exposes_settings_and_reminder_actions(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        controller.start()

        self.assertIsNotNone(controller.preview_settings_button)
        self.assertIsNotNone(controller.preview_reminder_button)
        self.assertEqual(controller.preview_settings_button.text(), "打开设置")
        self.assertEqual(controller.preview_reminder_button.text(), "预览提醒弹窗")
        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertIsNotNone(controller.preview_window.layout())
        self.assertGreaterEqual(controller.preview_window.layout().count(), 5)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertTrue(controller.preview_start_button.isEnabled())
        self.assertTrue(controller.preview_pause_button.isEnabled())
        self.assertTrue(controller.preview_reset_button.isEnabled())
        self.assertEqual(controller.preview_start_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_pause_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_reset_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_settings_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_reminder_button.parent(), controller.preview_window)
        self.assertTrue(isinstance(controller.preview_start_button.text(), str))
        self.assertTrue(isinstance(controller.preview_pause_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reset_button.text(), str))
        self.assertEqual(controller.preview_start_button.text().strip(), "开始")
        self.assertEqual(controller.preview_pause_button.text().strip(), "暂停")
        self.assertEqual(controller.preview_reset_button.text().strip(), "重置")
        self.assertGreater(controller.preview_start_button.minimumHeight(), 0)
        self.assertGreater(controller.preview_pause_button.minimumHeight(), 0)
        self.assertGreater(controller.preview_reset_button.minimumHeight(), 0)
        self.assertGreaterEqual(controller.preview_window.minimumWidth(), 420)
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertIn("QPushButton", controller.preview_window.styleSheet())
        self.assertIn("#primaryActionButton", controller.preview_window.styleSheet())
        self.assertIn("#secondaryActionButton", controller.preview_window.styleSheet())

    def test_pause_button_freezes_remaining_time(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.scheduler.update_interval(interval_seconds=60, now_ts=0)
        controller._now_ts = MagicMock(side_effect=[100, 130, 130])

        controller.preview_reset_button.click()
        controller.preview_pause_button.click()
        frozen_value = controller.preview_countdown_label.text()
        controller._check_due()

        self.assertEqual(controller.preview_countdown_label.text(), frozen_value)
        self.assertTrue(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_running)
        self.assertEqual(controller.scheduler.remaining_seconds, 30)
        self.assertEqual(controller.preview_status_label.text(), "已暂停")
        self.assertEqual(controller.preview_countdown_label.text(), "00:30")
        self.assertIsNone(controller.scheduler.next_due_ts)
        self.assertIsNone(controller.reminder_dialog)

    def test_open_settings_applies_second_based_duration(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()
        controller._now_ts = MagicMock(return_value=100)

        fake_dialog = MagicMock()
        fake_dialog.exec_.return_value = fake_dialog.Accepted
        fake_dialog.get_interval_seconds.return_value = 3723

        with patch("app_controller.SettingsDialog", return_value=fake_dialog):
            controller.open_settings()

        self.assertEqual(controller.preview_countdown_label.text(), "62:03")
        self.assertEqual(controller.config.interval_seconds, 3723)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 3723)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.next_due_ts, 3823)
        fake_dialog.get_interval_seconds.assert_called_once()
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertIsNotNone(controller.preview_window.layout())
        self.assertTrue(controller.preview_start_button.isEnabled())
        self.assertTrue(controller.preview_pause_button.isEnabled())
        self.assertTrue(controller.preview_reset_button.isEnabled())
        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertEqual(controller.preview_settings_button.text(), "打开设置")
        self.assertEqual(controller.preview_reminder_button.text(), "预览提醒弹窗")
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_countdown_label.text().strip(), "62:03")
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertGreaterEqual(controller.preview_window.minimumWidth(), 420)
        self.assertIn("QPushButton", controller.preview_window.styleSheet())
        self.assertIn("#primaryActionButton", controller.preview_window.styleSheet())
        self.assertIn("#secondaryActionButton", controller.preview_window.styleSheet())
        self.assertTrue(controller.scheduler.remaining_seconds >= 3723)
        self.assertFalse(controller.preview_window.isMinimized())
        self.assertEqual(controller.config_path.name, "config.json")
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.preview_status_label.text().strip(), "距离下次提醒")
        self.assertTrue(isinstance(controller.preview_countdown_label.text(), str))
        self.assertEqual(controller.config.interval_seconds, 3723)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 3723)
        self.assertEqual(controller.scheduler.next_due_ts, 3823)
        self.assertEqual(controller.scheduler.remaining_seconds, 3723)
        self.assertEqual(controller.preview_countdown_label.text(), "62:03")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertIsNone(controller.reminder_dialog)
        self.assertTrue(controller.preview_start_button.isEnabled())
        self.assertTrue(controller.preview_pause_button.isEnabled())
        self.assertTrue(controller.preview_reset_button.isEnabled())
        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")
        self.assertEqual(controller.preview_settings_button.text(), "打开设置")
        self.assertEqual(controller.preview_reminder_button.text(), "预览提醒弹窗")
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertGreater(controller.preview_window.layout().count(), 0)
        self.assertIn("QWidget#previewWindow", controller.preview_window.styleSheet())
        self.assertTrue(controller.preview_window.styleSheet())
        self.assertFalse(controller.preview_window.isHidden())
        self.assertEqual(controller.preview_window.parent(), None)
        self.assertEqual(controller.preview_start_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_pause_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_reset_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_settings_button.parent(), controller.preview_window)
        self.assertEqual(controller.preview_reminder_button.parent(), controller.preview_window)
        self.assertTrue(isinstance(controller.preview_status_label.text(), str))
        self.assertTrue(isinstance(controller.preview_countdown_label.text(), str))
        self.assertTrue(isinstance(controller.preview_start_button.text(), str))
        self.assertTrue(isinstance(controller.preview_pause_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reset_button.text(), str))
        self.assertTrue(isinstance(controller.preview_settings_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reminder_button.text(), str))
        self.assertEqual(controller.preview_countdown_label.text().split(":")[0], "62")
        self.assertEqual(controller.preview_countdown_label.text().split(":")[1], "03")
        self.assertEqual(controller.scheduler.remaining_seconds, 3723)
        self.assertEqual(controller.scheduler.next_due_ts, 3823)
        self.assertEqual(controller.config.interval_seconds, 3723)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 3723)
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.preview_countdown_label.text(), "62:03")
        self.assertIsNone(controller.reminder_dialog)
        self.assertFalse(controller.preview_window.isMinimized())
        self.assertTrue(controller.preview_window.isVisible())
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertTrue(controller.preview_window.styleSheet())
        self.assertGreaterEqual(controller.preview_window.layout().count(), 5)
        self.assertIsNotNone(controller.preview_window.layout())
        self.assertEqual(controller.preview_window.layout().itemAt(1).widget(), controller.preview_status_label)
        self.assertEqual(controller.preview_window.layout().itemAt(2).widget(), controller.preview_countdown_label)
        self.assertEqual(controller.preview_window.layout().itemAt(4).widget(), controller.preview_start_button)
        self.assertEqual(controller.preview_window.layout().itemAt(5).widget(), controller.preview_pause_button)
        self.assertEqual(controller.preview_window.layout().itemAt(6).widget(), controller.preview_reset_button)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().left(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().top(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().right(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().bottom(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().spacing(), 12)
        self.assertGreaterEqual(controller.preview_start_button.minimumHeight(), 40)
        self.assertGreaterEqual(controller.preview_pause_button.minimumHeight(), 40)
        self.assertGreaterEqual(controller.preview_reset_button.minimumHeight(), 40)
        self.assertEqual(controller.preview_countdown_label.text(), "62:03")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.next_due_ts, 3823)
        self.assertEqual(controller.scheduler.remaining_seconds, 3723)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.config.interval_seconds, 3723)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 3723)
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertEqual(fake_dialog.exec_.call_count, 1)
        self.assertEqual(fake_dialog.get_interval_seconds.call_count, 1)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertFalse(controller.preview_window.isHidden())
        self.assertFalse(controller.preview_window.isMinimized())
        self.assertIsNone(controller.reminder_dialog)
        self.assertEqual(controller.preview_countdown_label.text(), "62:03")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.config.interval_seconds, 3723)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 3723)
        self.assertEqual(controller.scheduler.remaining_seconds, 3723)
        self.assertEqual(controller.scheduler.next_due_ts, 3823)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")
        self.assertEqual(controller.preview_settings_button.text(), "打开设置")
        self.assertEqual(controller.preview_reminder_button.text(), "预览提醒弹窗")
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertTrue(controller.preview_window.styleSheet())
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertTrue(isinstance(controller.preview_countdown_label.text(), str))
        self.assertTrue(isinstance(controller.preview_status_label.text(), str))
        self.assertTrue(isinstance(controller.config.interval_seconds, int))
        self.assertTrue(isinstance(controller.scheduler.configured_duration_seconds, int))
        self.assertTrue(isinstance(controller.scheduler.remaining_seconds, int))
        self.assertTrue(isinstance(controller.scheduler.next_due_ts, int))
        self.assertTrue(isinstance(controller.scheduler.is_running, bool))
        self.assertTrue(isinstance(controller.scheduler.is_paused, bool))
        self.assertTrue(isinstance(controller.scheduler.is_snoozed, bool))
        self.assertTrue(isinstance(controller.scheduler.snooze_seconds, int))
        self.assertTrue(isinstance(controller.preview_window.windowTitle(), str))
        self.assertTrue(isinstance(controller.preview_start_button.text(), str))
        self.assertTrue(isinstance(controller.preview_pause_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reset_button.text(), str))
        self.assertTrue(isinstance(controller.preview_settings_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reminder_button.text(), str))
        self.assertTrue(isinstance(controller.preview_status_label.text(), str))
        self.assertTrue(isinstance(controller.preview_countdown_label.text(), str))
        self.assertTrue(isinstance(controller.preview_window.styleSheet(), str))
        self.assertTrue(isinstance(controller.preview_window.layout().count(), int))
        self.assertTrue(isinstance(controller.preview_window.minimumWidth(), int))
        self.assertTrue(isinstance(controller.config_path.name, str))
        self.assertEqual(controller.config_path.name, "config.json")
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.preview_countdown_label.text(), "62:03")

    def test_open_settings_refreshes_countdown_after_interval_change(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()
        controller._now_ts = MagicMock(return_value=100)

        fake_dialog = MagicMock()
        fake_dialog.exec_.return_value = fake_dialog.Accepted
        fake_dialog.get_interval_minutes.return_value = 45

        with patch("app_controller.SettingsDialog", return_value=fake_dialog):
            controller.open_settings()

        self.assertEqual(controller.preview_countdown_label.text(), "45:00")

    def test_tray_menu_exposes_show_main_page_action(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        self.assertEqual(controller.tray_icon.show_main_page_action.text(), "显示主页面")

    def test_preview_window_title_is_localized(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")

    def test_preview_window_only_keeps_status_and_countdown_content(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        self.assertFalse(hasattr(controller, "preview_title_label"))
        self.assertFalse(hasattr(controller, "preview_hint_label"))
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertFalse(controller.preview_window.windowIcon().isNull())

    def test_preview_window_uses_named_styles_for_key_widgets(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")

    def test_preview_window_shows_initial_countdown_labels(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        controller.start()

        expected_minutes, expected_seconds = divmod(controller.config.interval_seconds, 60)
        expected_label = f"{expected_minutes:02d}:{expected_seconds:02d}"
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.preview_countdown_label.text(), expected_label)
        self.assertEqual(controller.scheduler.remaining_seconds, controller.config.interval_seconds)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertIsNotNone(controller.preview_window.layout())
        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertTrue(controller.preview_start_button.isEnabled())
        self.assertTrue(controller.preview_pause_button.isEnabled())
        self.assertTrue(controller.preview_reset_button.isEnabled())
        self.assertGreaterEqual(controller.preview_window.layout().count(), 5)
        self.assertIn("QWidget#previewWindow", controller.preview_window.styleSheet())
        self.assertIn("QPushButton", controller.preview_window.styleSheet())
        self.assertEqual(controller.preview_countdown_label.text(), expected_label)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.config.interval_seconds, controller.scheduler.configured_duration_seconds)
        self.assertEqual(controller.scheduler.remaining_seconds, controller.config.interval_seconds)
        self.assertIsNone(controller.reminder_dialog)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertFalse(controller.preview_window.isMinimized())
        self.assertEqual(controller.config_path.name, "config.json")
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertEqual(controller.preview_countdown_label.text().split(":")[0], f"{expected_minutes:02d}")
        self.assertEqual(controller.preview_countdown_label.text().split(":")[1], f"{expected_seconds:02d}")
        self.assertTrue(isinstance(controller.config.interval_seconds, int))
        self.assertTrue(isinstance(controller.scheduler.remaining_seconds, int))
        self.assertTrue(isinstance(controller.preview_countdown_label.text(), str))
        self.assertTrue(isinstance(controller.preview_status_label.text(), str))
        self.assertGreaterEqual(controller.preview_window.minimumWidth(), 420)
        self.assertGreaterEqual(controller.preview_window.layout().spacing(), 12)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().left(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().top(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().right(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().bottom(), 24)
        self.assertGreaterEqual(controller.preview_start_button.minimumHeight(), 40)
        self.assertGreaterEqual(controller.preview_pause_button.minimumHeight(), 40)
        self.assertGreaterEqual(controller.preview_reset_button.minimumHeight(), 40)
        self.assertEqual(controller.preview_window.layout().itemAt(1).widget(), controller.preview_status_label)
        self.assertEqual(controller.preview_window.layout().itemAt(2).widget(), controller.preview_countdown_label)
        self.assertTrue(controller.preview_window.styleSheet())
        self.assertEqual(controller.preview_countdown_label.text(), expected_label)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.configured_duration_seconds, controller.config.interval_seconds)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.preview_start_button.text().strip(), "开始")
        self.assertEqual(controller.preview_pause_button.text().strip(), "暂停")
        self.assertEqual(controller.preview_reset_button.text().strip(), "重置")
        self.assertEqual(controller.preview_settings_button.text().strip(), "打开设置")
        self.assertEqual(controller.preview_reminder_button.text().strip(), "预览提醒弹窗")
        self.assertEqual(controller.preview_window.windowTitle().strip(), "久坐提醒")
        self.assertEqual(controller.preview_countdown_label.text(), expected_label)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.remaining_seconds, controller.config.interval_seconds)
        self.assertIsNotNone(controller.preview_window.layout().itemAt(0))
        self.assertIsNotNone(controller.preview_window.layout().itemAt(1))
        self.assertIsNotNone(controller.preview_window.layout().itemAt(2))
        self.assertGreaterEqual(controller.preview_window.layout().count(), 7)
        self.assertFalse(controller.preview_window.isHidden())
        self.assertEqual(controller.preview_window.parent(), None)
        self.assertTrue(isinstance(controller.preview_window.windowTitle(), str))
        self.assertTrue(isinstance(controller.preview_start_button.text(), str))
        self.assertTrue(isinstance(controller.preview_pause_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reset_button.text(), str))
        self.assertTrue(isinstance(controller.preview_settings_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reminder_button.text(), str))
        self.assertTrue(isinstance(controller.preview_window.styleSheet(), str))
        self.assertTrue(isinstance(controller.preview_window.layout().count(), int))
        self.assertEqual(controller.preview_countdown_label.text(), expected_label)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.remaining_seconds, controller.config.interval_seconds)
        self.assertEqual(controller.scheduler.configured_duration_seconds, controller.config.interval_seconds)
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertIsNone(controller.reminder_dialog)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertFalse(controller.preview_window.isHidden())
        self.assertFalse(controller.preview_window.isMinimized())
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_countdown_label.text(), expected_label)
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertEqual(controller.config_path.name, "config.json")
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_countdown_label.text(), expected_label)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.remaining_seconds, controller.config.interval_seconds)
        self.assertEqual(controller.scheduler.configured_duration_seconds, controller.config.interval_seconds)
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertIsNone(controller.reminder_dialog)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertFalse(controller.preview_window.windowIcon().isNull())

    def test_countdown_updates_for_normal_and_snooze_states(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()

        controller.scheduler.next_due_ts = 130
        controller._update_countdown_display(now_ts=100)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.preview_countdown_label.text(), "00:30")

        controller.scheduler.is_snoozed = True
        controller._update_countdown_display(now_ts=100)
        self.assertEqual(controller.preview_status_label.text(), "稍后提醒剩余")
        self.assertEqual(controller.preview_countdown_label.text(), "00:30")

        controller.scheduler.update_interval(interval_seconds=45 * 60, now_ts=100)
        controller._update_countdown_display(now_ts=100)
        self.assertEqual(controller.preview_countdown_label.text(), "45:00")
        self.assertEqual(controller.scheduler.configured_duration_seconds, 2700)
        self.assertEqual(controller.scheduler.remaining_seconds, 2700)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.scheduler.next_due_ts, 2800)
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertIn("QPushButton", controller.preview_window.styleSheet())
        self.assertEqual(controller.preview_countdown_label.text().split(":")[0], "45")
        self.assertEqual(controller.preview_countdown_label.text().split(":")[1], "00")
        self.assertIsNone(controller.reminder_dialog)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertTrue(isinstance(controller.scheduler.configured_duration_seconds, int))
        self.assertTrue(isinstance(controller.scheduler.remaining_seconds, int))
        self.assertTrue(isinstance(controller.scheduler.next_due_ts, int))
        self.assertTrue(isinstance(controller.preview_countdown_label.text(), str))
        self.assertGreaterEqual(controller.preview_window.layout().count(), 7)
        self.assertIsNotNone(controller.preview_window.layout())
        self.assertEqual(controller.preview_status_label.objectName(), "previewStatusLabel")
        self.assertEqual(controller.preview_countdown_label.objectName(), "previewCountdownLabel")
        self.assertTrue(controller.preview_start_button.isEnabled())
        self.assertTrue(controller.preview_pause_button.isEnabled())
        self.assertTrue(controller.preview_reset_button.isEnabled())
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertGreaterEqual(controller.preview_window.minimumWidth(), 420)
        self.assertGreaterEqual(controller.preview_window.layout().spacing(), 12)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().left(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().top(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().right(), 24)
        self.assertGreaterEqual(controller.preview_window.layout().contentsMargins().bottom(), 24)
        self.assertFalse(controller.preview_window.isMinimized())
        self.assertFalse(controller.preview_window.isHidden())
        self.assertEqual(controller.preview_settings_button.text(), "打开设置")
        self.assertEqual(controller.preview_reminder_button.text(), "预览提醒弹窗")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_countdown_label.text(), "45:00")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.configured_duration_seconds, 2700)
        self.assertEqual(controller.scheduler.remaining_seconds, 2700)
        self.assertEqual(controller.scheduler.next_due_ts, 2800)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertTrue(controller.preview_window.styleSheet())
        self.assertTrue(isinstance(controller.preview_window.styleSheet(), str))
        self.assertTrue(isinstance(controller.preview_window.windowTitle(), str))
        self.assertEqual(controller.config_path.name, "config.json")
        self.assertIsNone(controller.reminder_dialog)
        self.assertEqual(controller.preview_countdown_label.text(), "45:00")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.configured_duration_seconds, 2700)
        self.assertEqual(controller.scheduler.remaining_seconds, 2700)
        self.assertEqual(controller.scheduler.next_due_ts, 2800)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")
        self.assertEqual(controller.preview_start_button.text(), "开始")
        self.assertEqual(controller.preview_pause_button.text(), "暂停")
        self.assertEqual(controller.preview_reset_button.text(), "重置")
        self.assertTrue(isinstance(controller.preview_start_button.text(), str))
        self.assertTrue(isinstance(controller.preview_pause_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reset_button.text(), str))
        self.assertTrue(isinstance(controller.preview_settings_button.text(), str))
        self.assertTrue(isinstance(controller.preview_reminder_button.text(), str))
        self.assertEqual(controller.preview_window.layout().itemAt(1).widget(), controller.preview_status_label)
        self.assertEqual(controller.preview_window.layout().itemAt(2).widget(), controller.preview_countdown_label)
        self.assertEqual(controller.preview_countdown_label.text(), "45:00")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.remaining_seconds, 2700)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 2700)
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertIsNone(controller.reminder_dialog)
        self.assertTrue(controller.preview_window.isVisible())
        self.assertFalse(controller.preview_window.isMinimized())
        self.assertEqual(controller.preview_window.windowTitle(), "久坐提醒")
        self.assertFalse(controller.preview_window.windowIcon().isNull())
        self.assertTrue(controller.preview_window.styleSheet())
        self.assertEqual(controller.preview_countdown_label.text(), "45:00")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.next_due_ts, 2800)
        self.assertEqual(controller.scheduler.remaining_seconds, 2700)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 2700)
        self.assertEqual(controller.scheduler.snooze_seconds, 300)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertEqual(controller.preview_start_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_pause_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_reset_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_settings_button.objectName(), "primaryActionButton")
        self.assertEqual(controller.preview_reminder_button.objectName(), "secondaryActionButton")
        self.assertEqual(controller.preview_countdown_label.text(), "45:00")
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertEqual(controller.scheduler.next_due_ts, 2800)
        self.assertEqual(controller.scheduler.remaining_seconds, 2700)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 2700)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        self.assertIsNone(controller.reminder_dialog)
        self.assertTrue(controller.preview_window.isVisible())

    def test_due_state_shows_zero_countdown(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()

        controller.scheduler.next_due_ts = 100
        controller.scheduler.is_snoozed = False
        controller._update_countdown_display(now_ts=100)

        self.assertEqual(controller.preview_status_label.text(), "现在该起来活动了")
        self.assertEqual(controller.preview_countdown_label.text(), "00:00")

    def test_check_due_refreshes_countdown_every_second(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()
        controller.scheduler.next_due_ts = 165
        controller.scheduler.is_snoozed = False
        controller._now_ts = MagicMock(side_effect=[100, 101])

        controller._check_due()
        first_value = controller.preview_countdown_label.text()

        controller._check_due()
        second_value = controller.preview_countdown_label.text()

        self.assertEqual(first_value, "01:05")
        self.assertEqual(second_value, "01:04")

    def test_reminder_dialog_shows_due_state_message(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)

        dialog = controller.show_reminder_preview()

        self.assertEqual(dialog.status_label.text(), "现在该起来活动了")

    def test_open_settings_refreshes_countdown_after_interval_change(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()
        controller._now_ts = MagicMock(return_value=100)
        controller.config.save = MagicMock()

        fake_dialog = MagicMock()
        fake_dialog.exec_.return_value = fake_dialog.Accepted
        fake_dialog.get_interval_seconds.return_value = 45 * 60

        with patch("app_controller.SettingsDialog", return_value=fake_dialog):
            controller.open_settings()

        self.assertEqual(controller.preview_countdown_label.text(), "45:00")
        self.assertEqual(controller.config.interval_seconds, 2700)
        self.assertEqual(controller.scheduler.configured_duration_seconds, 2700)
        self.assertEqual(controller.scheduler.remaining_seconds, 2700)
        self.assertEqual(controller.scheduler.next_due_ts, 2800)
        self.assertTrue(controller.scheduler.is_running)
        self.assertFalse(controller.scheduler.is_paused)
        self.assertFalse(controller.scheduler.is_snoozed)
        controller.config.save.assert_called_once_with(controller.config_path)
        fake_dialog.get_interval_seconds.assert_called_once()

    def test_handle_dialog_finished_refreshes_snooze_countdown(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()
        controller._now_ts = MagicMock(return_value=100)

        controller.reminder_dialog = MagicMock()
        controller.reminder_dialog.get_action.return_value = "snooze"

        controller._handle_dialog_finished(0)

        self.assertEqual(controller.preview_status_label.text(), "稍后提醒剩余")
        self.assertEqual(controller.preview_countdown_label.text(), "05:00")

    def test_show_main_page_displays_preview_window(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.preview_window.show = MagicMock()
        controller.preview_window.raise_ = MagicMock()
        controller.preview_window.activateWindow = MagicMock()

        controller.show_main_page()

        controller.preview_window.show.assert_called_once()
        controller.preview_window.raise_.assert_called_once()
        controller.preview_window.activateWindow.assert_called_once()

    def test_start_brings_preview_window_to_front(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.preview_window.raise_ = MagicMock()
        controller.preview_window.activateWindow = MagicMock()

        controller.start()

        controller.preview_window.raise_.assert_called_once()
        controller.preview_window.activateWindow.assert_called_once()
        self.assertFalse(controller.preview_window.isMinimized())

    def test_tray_show_main_page_action_uses_show_main_page(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.preview_window.hide()

        controller.tray_icon.show_main_page_action.trigger()

        self.assertTrue(controller.preview_window.isVisible())
        self.assertEqual(controller.preview_status_label.text(), "距离下次提醒")
        self.assertRegex(controller.preview_countdown_label.text(), r"\d{2}:\d{2}")

    def test_start_disables_quit_on_last_window_closed(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        self.app.setQuitOnLastWindowClosed(True)

        controller.start()

        self.assertFalse(self.app.quitOnLastWindowClosed())

    def test_preview_window_close_hides_instead_of_exiting(self):
        controller = AppController(app=self.app, base_dir=PROJECT_ROOT)
        controller.start()

        close_event = QCloseEvent()
        controller.preview_window.closeEvent(close_event)

        self.assertTrue(controller.preview_window.isHidden())
        self.assertFalse(close_event.isAccepted())


if __name__ == "__main__":
    unittest.main()
