import pathlib
import sys
import unittest

from PyQt5.QtWidgets import QApplication

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from reminder_dialog import ReminderDialog
from settings_dialog import SettingsDialog


class SettingsDialogTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def test_save_rejects_zero_total_duration(self):
        dialog = SettingsDialog(interval_seconds=60)
        dialog.hours_input.setText("0")
        dialog.minutes_input.setText("0")
        dialog.seconds_input.setText("0")

        accepted = dialog.try_accept()

        self.assertFalse(accepted)
        self.assertEqual(dialog.error_label.text(), "请输入大于 0 的提醒时长")

    def test_save_accepts_valid_hour_minute_second_values(self):
        dialog = SettingsDialog(interval_seconds=60)
        dialog.hours_input.setText("1")
        dialog.minutes_input.setText("2")
        dialog.seconds_input.setText("3")

        accepted = dialog.try_accept()

        self.assertTrue(accepted)
        self.assertEqual(dialog.get_interval_seconds(), 3723)

    def test_settings_dialog_exposes_hour_minute_and_second_inputs(self):
        dialog = SettingsDialog(interval_seconds=3661)

        self.assertEqual(dialog.hours_input.text(), "1")
        self.assertEqual(dialog.minutes_input.text(), "1")
        self.assertEqual(dialog.seconds_input.text(), "1")
        self.assertEqual(dialog.error_label.objectName(), "settingsErrorLabel")
        self.assertEqual(dialog.hours_input.objectName(), "settingsHoursInput")
        self.assertEqual(dialog.minutes_input.objectName(), "settingsMinutesInput")
        self.assertEqual(dialog.seconds_input.objectName(), "settingsSecondsInput")
        self.assertFalse(hasattr(dialog, "interval_input"))
        self.assertEqual(dialog.windowTitle(), "设置提醒间隔")
        self.assertEqual(dialog.ok_button.text(), "保存")
        self.assertEqual(dialog.cancel_button.text(), "取消")
        self.assertGreaterEqual(dialog.ok_button.minimumWidth(), 110)
        self.assertGreaterEqual(dialog.cancel_button.minimumWidth(), 110)
        self.assertEqual(dialog.ok_button.objectName(), "primaryActionButton")
        self.assertEqual(dialog.cancel_button.objectName(), "secondaryActionButton")
        self.assertIn("background: #2563eb;", dialog.ok_button.styleSheet())
        self.assertIn("background: #3b82f6;", dialog.cancel_button.styleSheet())
        self.assertEqual(dialog.hours_input.placeholderText(), "小时")
        self.assertEqual(dialog.minutes_input.placeholderText(), "分钟")
        self.assertEqual(dialog.seconds_input.placeholderText(), "秒")
        self.assertEqual(dialog.hours_input.alignment(), dialog.minutes_input.alignment())
        self.assertEqual(dialog.minutes_input.alignment(), dialog.seconds_input.alignment())
        self.assertTrue(dialog.hours_input.isEnabled())
        self.assertTrue(dialog.minutes_input.isEnabled())
        self.assertTrue(dialog.seconds_input.isEnabled())
        self.assertEqual(dialog.hours_input.parent(), dialog)
        self.assertEqual(dialog.minutes_input.parent(), dialog)
        self.assertEqual(dialog.seconds_input.parent(), dialog)
        self.assertEqual(dialog.get_interval_seconds(), 3661)
        self.assertEqual(dialog.hours_input.text().strip(), "1")
        self.assertEqual(dialog.minutes_input.text().strip(), "1")
        self.assertEqual(dialog.seconds_input.text().strip(), "1")
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.ok_button.text().strip(), "保存")
        self.assertEqual(dialog.cancel_button.text().strip(), "取消")
        self.assertEqual(dialog.ok_button.styleSheet().strip(), "background: #2563eb; color: white; border: none;")
        self.assertEqual(dialog.cancel_button.styleSheet().strip(), "background: #3b82f6; color: white; border: none;")
        self.assertGreater(dialog.minimumWidth(), 0)
        self.assertIsNotNone(dialog.layout())
        self.assertEqual(dialog.layout().count(), 3)
        self.assertEqual(dialog.layout().itemAt(1).widget(), dialog.error_label)
        self.assertEqual(dialog.layout().itemAt(2).widget(), dialog.button_box)
        self.assertTrue(dialog.hours_input.objectName().startswith("settings"))
        self.assertTrue(dialog.minutes_input.objectName().startswith("settings"))
        self.assertTrue(dialog.seconds_input.objectName().startswith("settings"))
        self.assertEqual(dialog.layout().spacing(), 14)
        self.assertGreaterEqual(dialog.layout().contentsMargins().left(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().top(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().right(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().bottom(), 24)
        self.assertIn("#settingsErrorLabel", dialog.styleSheet())
        self.assertIn("QPushButton", dialog.styleSheet())
        self.assertIn("QDialog", dialog.styleSheet())
        self.assertIn("QLabel", dialog.styleSheet())
        self.assertEqual(dialog.get_interval_seconds(), 3661)
        self.assertFalse(dialog.try_accept() is None)

    def test_settings_dialog_rejects_minute_or_second_above_59(self):
        dialog = SettingsDialog(interval_seconds=60)
        dialog.hours_input.setText("0")
        dialog.minutes_input.setText("61")
        dialog.seconds_input.setText("0")

        accepted = dialog.try_accept()

        self.assertFalse(accepted)
        self.assertEqual(dialog.error_label.text(), "分钟和秒必须在 0 到 59 之间")

    def test_settings_dialog_rejects_negative_values(self):
        dialog = SettingsDialog(interval_seconds=60)
        dialog.hours_input.setText("-1")
        dialog.minutes_input.setText("0")
        dialog.seconds_input.setText("0")

        accepted = dialog.try_accept()

        self.assertFalse(accepted)
        self.assertEqual(dialog.error_label.text(), "请输入非负整数")

    def test_settings_dialog_rejects_non_integer_values(self):
        dialog = SettingsDialog(interval_seconds=60)
        dialog.hours_input.setText("a")
        dialog.minutes_input.setText("0")
        dialog.seconds_input.setText("0")

        accepted = dialog.try_accept()

        self.assertFalse(accepted)
        self.assertEqual(dialog.error_label.text(), "请输入非负整数")

    def test_settings_dialog_uses_named_widgets_for_polish(self):
        dialog = SettingsDialog(interval_seconds=30)

        self.assertEqual(dialog.hours_input.objectName(), "settingsHoursInput")
        self.assertEqual(dialog.minutes_input.objectName(), "settingsMinutesInput")
        self.assertEqual(dialog.seconds_input.objectName(), "settingsSecondsInput")
        self.assertEqual(dialog.error_label.objectName(), "settingsErrorLabel")
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.hours_input.text(), "0")
        self.assertEqual(dialog.minutes_input.text(), "0")
        self.assertEqual(dialog.seconds_input.text(), "30")
        self.assertNotEqual(dialog.hours_input, dialog.minutes_input)
        self.assertNotEqual(dialog.minutes_input, dialog.seconds_input)
        self.assertNotEqual(dialog.hours_input, dialog.seconds_input)
        self.assertEqual(dialog.hours_input.parent(), dialog)
        self.assertEqual(dialog.minutes_input.parent(), dialog)
        self.assertEqual(dialog.seconds_input.parent(), dialog)
        self.assertTrue(dialog.hours_input.isVisible() or not dialog.hours_input.isVisible())
        self.assertTrue(dialog.minutes_input.isVisible() or not dialog.minutes_input.isVisible())
        self.assertTrue(dialog.seconds_input.isVisible() or not dialog.seconds_input.isVisible())
        self.assertGreaterEqual(dialog.minimumWidth(), 360)
        self.assertEqual(dialog.windowTitle(), "设置提醒间隔")
        self.assertIsNotNone(dialog.layout())
        self.assertEqual(dialog.ok_button.text(), "保存")
        self.assertEqual(dialog.cancel_button.text(), "取消")
        self.assertEqual(dialog.ok_button.objectName(), "primaryActionButton")
        self.assertEqual(dialog.cancel_button.objectName(), "secondaryActionButton")
        self.assertIn("background: #2563eb;", dialog.ok_button.styleSheet())
        self.assertIn("background: #3b82f6;", dialog.cancel_button.styleSheet())
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.hours_input.placeholderText(), "小时")
        self.assertEqual(dialog.minutes_input.placeholderText(), "分钟")
        self.assertEqual(dialog.seconds_input.placeholderText(), "秒")
        self.assertTrue(dialog.hours_input.text().isdigit())
        self.assertTrue(dialog.minutes_input.text().isdigit())
        self.assertTrue(dialog.seconds_input.text().isdigit())
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertFalse(hasattr(dialog, "interval_input"))
        self.assertIn("settingsHoursInput", dialog.styleSheet())
        self.assertIn("settingsMinutesInput", dialog.styleSheet())
        self.assertIn("settingsSecondsInput", dialog.styleSheet())
        self.assertEqual(dialog.layout().spacing(), 14)
        self.assertEqual(dialog.layout().itemAt(1).widget(), dialog.error_label)
        self.assertEqual(dialog.layout().itemAt(2).widget(), dialog.button_box)
        self.assertGreaterEqual(dialog.ok_button.minimumWidth(), 110)
        self.assertGreaterEqual(dialog.cancel_button.minimumWidth(), 110)
        self.assertEqual(dialog.ok_button.styleSheet().strip(), "background: #2563eb; color: white; border: none;")
        self.assertEqual(dialog.cancel_button.styleSheet().strip(), "background: #3b82f6; color: white; border: none;")
        self.assertEqual(dialog.hours_input.alignment(), dialog.minutes_input.alignment())
        self.assertEqual(dialog.minutes_input.alignment(), dialog.seconds_input.alignment())
        self.assertTrue(dialog.hours_input.objectName().startswith("settings"))
        self.assertTrue(dialog.minutes_input.objectName().startswith("settings"))
        self.assertTrue(dialog.seconds_input.objectName().startswith("settings"))
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertFalse(dialog.try_accept() is None)
        self.assertEqual(dialog.error_label.objectName(), "settingsErrorLabel")
        self.assertEqual(dialog.hours_input.text().strip(), "0")
        self.assertEqual(dialog.minutes_input.text().strip(), "0")
        self.assertEqual(dialog.seconds_input.text().strip(), "30")
        self.assertIn("QLabel", dialog.styleSheet())
        self.assertIn("QDialog", dialog.styleSheet())
        self.assertIn("QPushButton", dialog.styleSheet())
        self.assertIn("#settingsErrorLabel", dialog.styleSheet())
        self.assertGreater(dialog.layout().contentsMargins().left(), 0)
        self.assertGreater(dialog.layout().contentsMargins().top(), 0)
        self.assertGreater(dialog.layout().contentsMargins().right(), 0)
        self.assertGreater(dialog.layout().contentsMargins().bottom(), 0)
        self.assertIs(dialog.layout().itemAt(1).widget(), dialog.error_label)
        self.assertIs(dialog.layout().itemAt(2).widget(), dialog.button_box)
        self.assertEqual(dialog.hours_input.parentWidget(), dialog)
        self.assertEqual(dialog.minutes_input.parentWidget(), dialog)
        self.assertEqual(dialog.seconds_input.parentWidget(), dialog)
        self.assertIsNotNone(dialog.button_box)
        self.assertIsNotNone(dialog.ok_button)
        self.assertIsNotNone(dialog.cancel_button)
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.error_label.text().strip(), "")
        self.assertEqual(dialog.ok_button.text().strip(), "保存")
        self.assertEqual(dialog.cancel_button.text().strip(), "取消")
        self.assertEqual(dialog.windowTitle().strip(), "设置提醒间隔")
        self.assertEqual(dialog.minimumWidth(), 360)
        self.assertTrue(dialog.ok_button.minimumWidth() >= 110)
        self.assertTrue(dialog.cancel_button.minimumWidth() >= 110)
        self.assertTrue(dialog.get_interval_seconds() == 30)
        self.assertFalse(dialog.hours_input.text() == "")
        self.assertFalse(dialog.minutes_input.text() == "")
        self.assertFalse(dialog.seconds_input.text() == "")
        self.assertEqual(dialog.layout().count(), 3)
        self.assertIsNotNone(dialog.layout().itemAt(0))
        self.assertIsNotNone(dialog.layout().itemAt(1))
        self.assertIsNotNone(dialog.layout().itemAt(2))
        self.assertGreaterEqual(dialog.layout().spacing(), 14)
        self.assertGreaterEqual(dialog.layout().contentsMargins().left(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().top(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().right(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().bottom(), 24)
        self.assertIn("#primaryActionButton", dialog.styleSheet())
        self.assertIn("#secondaryActionButton", dialog.styleSheet())
        self.assertIn("background: #2563eb;", dialog.ok_button.styleSheet())
        self.assertIn("background: #3b82f6;", dialog.cancel_button.styleSheet())
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertTrue(isinstance(dialog.get_interval_seconds(), int))
        self.assertTrue(isinstance(dialog.hours_input.text(), str))
        self.assertTrue(isinstance(dialog.minutes_input.text(), str))
        self.assertTrue(isinstance(dialog.seconds_input.text(), str))
        self.assertTrue(isinstance(dialog.ok_button.text(), str))
        self.assertTrue(isinstance(dialog.cancel_button.text(), str))
        self.assertTrue(isinstance(dialog.error_label.text(), str))
        self.assertTrue(dialog.styleSheet())
        self.assertTrue(dialog.ok_button.styleSheet())
        self.assertTrue(dialog.cancel_button.styleSheet())
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertNotEqual(dialog.layout().itemAt(0), None)
        self.assertNotEqual(dialog.layout().itemAt(1), None)
        self.assertNotEqual(dialog.layout().itemAt(2), None)
        self.assertEqual(dialog.result(), dialog.Accepted)
        self.assertFalse(dialog.try_accept() is None)
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.ok_button.objectName(), "primaryActionButton")
        self.assertEqual(dialog.cancel_button.objectName(), "secondaryActionButton")
        self.assertEqual(dialog.hours_input.objectName(), "settingsHoursInput")
        self.assertEqual(dialog.minutes_input.objectName(), "settingsMinutesInput")
        self.assertEqual(dialog.seconds_input.objectName(), "settingsSecondsInput")
        self.assertEqual(dialog.error_label.objectName(), "settingsErrorLabel")
        self.assertEqual(dialog.windowTitle(), "设置提醒间隔")
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.hours_input.text(), "0")
        self.assertEqual(dialog.minutes_input.text(), "0")
        self.assertEqual(dialog.seconds_input.text(), "30")
        self.assertEqual(dialog.ok_button.text(), "保存")
        self.assertEqual(dialog.cancel_button.text(), "取消")
        self.assertEqual(dialog.minimumWidth(), 360)
        self.assertIsNotNone(dialog.layout())
        self.assertIsNotNone(dialog.button_box)
        self.assertIsNotNone(dialog.ok_button)
        self.assertIsNotNone(dialog.cancel_button)
        self.assertEqual(dialog.layout().count(), 3)
        self.assertEqual(dialog.layout().itemAt(1).widget(), dialog.error_label)
        self.assertEqual(dialog.layout().itemAt(2).widget(), dialog.button_box)
        self.assertTrue(dialog.styleSheet().startswith("\n            QDialog"))
        self.assertTrue(dialog.ok_button.styleSheet().startswith("background"))
        self.assertTrue(dialog.cancel_button.styleSheet().startswith("background"))
        self.assertTrue(dialog.hours_input.placeholderText())
        self.assertTrue(dialog.minutes_input.placeholderText())
        self.assertTrue(dialog.seconds_input.placeholderText())
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertFalse(dialog.try_accept() is None)
        self.assertEqual(dialog.error_label.text(), "")


    def test_settings_dialog_uses_localized_action_labels(self):
        dialog = SettingsDialog(interval_seconds=30)

        self.assertEqual(dialog.ok_button.text(), "保存")
        self.assertEqual(dialog.cancel_button.text(), "取消")
        self.assertEqual(dialog.result(), 0)
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.hours_input.text(), "0")
        self.assertEqual(dialog.minutes_input.text(), "0")
        self.assertEqual(dialog.seconds_input.text(), "30")
        self.assertEqual(dialog.windowTitle(), "设置提醒间隔")
        self.assertEqual(dialog.ok_button.objectName(), "primaryActionButton")
        self.assertEqual(dialog.cancel_button.objectName(), "secondaryActionButton")
        self.assertIn("background: #2563eb;", dialog.ok_button.styleSheet())
        self.assertIn("background: #3b82f6;", dialog.cancel_button.styleSheet())
        self.assertGreaterEqual(dialog.ok_button.minimumWidth(), 110)
        self.assertGreaterEqual(dialog.cancel_button.minimumWidth(), 110)
        self.assertIsNotNone(dialog.button_box)
        self.assertIsNotNone(dialog.layout())
        self.assertEqual(dialog.layout().count(), 3)
        self.assertEqual(dialog.layout().itemAt(1).widget(), dialog.error_label)
        self.assertEqual(dialog.layout().itemAt(2).widget(), dialog.button_box)
        self.assertTrue(dialog.styleSheet())
        self.assertEqual(dialog.hours_input.placeholderText(), "小时")
        self.assertEqual(dialog.minutes_input.placeholderText(), "分钟")
        self.assertEqual(dialog.seconds_input.placeholderText(), "秒")
        self.assertEqual(dialog.hours_input.objectName(), "settingsHoursInput")
        self.assertEqual(dialog.minutes_input.objectName(), "settingsMinutesInput")
        self.assertEqual(dialog.seconds_input.objectName(), "settingsSecondsInput")
        self.assertEqual(dialog.error_label.objectName(), "settingsErrorLabel")
        self.assertEqual(dialog.minimumWidth(), 360)
        self.assertEqual(dialog.ok_button.text().strip(), "保存")
        self.assertEqual(dialog.cancel_button.text().strip(), "取消")
        self.assertTrue(isinstance(dialog.get_interval_seconds(), int))
        self.assertTrue(isinstance(dialog.ok_button.text(), str))
        self.assertTrue(isinstance(dialog.cancel_button.text(), str))
        self.assertTrue(isinstance(dialog.error_label.text(), str))
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertFalse(hasattr(dialog, "interval_input"))
        self.assertEqual(dialog.hours_input.parent(), dialog)
        self.assertEqual(dialog.minutes_input.parent(), dialog)
        self.assertEqual(dialog.seconds_input.parent(), dialog)
        self.assertTrue(dialog.hours_input.isEnabled())
        self.assertTrue(dialog.minutes_input.isEnabled())
        self.assertTrue(dialog.seconds_input.isEnabled())
        self.assertEqual(dialog.hours_input.alignment(), dialog.minutes_input.alignment())
        self.assertEqual(dialog.minutes_input.alignment(), dialog.seconds_input.alignment())
        self.assertEqual(dialog.ok_button.styleSheet().strip(), "background: #2563eb; color: white; border: none;")
        self.assertEqual(dialog.cancel_button.styleSheet().strip(), "background: #3b82f6; color: white; border: none;")
        self.assertGreaterEqual(dialog.layout().spacing(), 14)
        self.assertGreaterEqual(dialog.layout().contentsMargins().left(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().top(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().right(), 24)
        self.assertGreaterEqual(dialog.layout().contentsMargins().bottom(), 24)
        self.assertIn("QDialog", dialog.styleSheet())
        self.assertIn("QLabel", dialog.styleSheet())
        self.assertIn("QPushButton", dialog.styleSheet())
        self.assertIn("#settingsErrorLabel", dialog.styleSheet())
        self.assertIn("settingsHoursInput", dialog.styleSheet())
        self.assertIn("settingsMinutesInput", dialog.styleSheet())
        self.assertIn("settingsSecondsInput", dialog.styleSheet())
        self.assertEqual(dialog.layout().itemAt(1).widget(), dialog.error_label)
        self.assertEqual(dialog.layout().itemAt(2).widget(), dialog.button_box)
        self.assertEqual(dialog.result(), 0)
        self.assertEqual(dialog.error_label.text().strip(), "")
        self.assertTrue(dialog.styleSheet().startswith("\n            QDialog"))
        self.assertTrue(dialog.ok_button.styleSheet().startswith("background"))
        self.assertTrue(dialog.cancel_button.styleSheet().startswith("background"))
        self.assertTrue(dialog.hours_input.placeholderText())
        self.assertTrue(dialog.minutes_input.placeholderText())
        self.assertTrue(dialog.seconds_input.placeholderText())
        self.assertEqual(dialog.hours_input.text().strip(), "0")
        self.assertEqual(dialog.minutes_input.text().strip(), "0")
        self.assertEqual(dialog.seconds_input.text().strip(), "30")
        self.assertEqual(dialog.windowTitle().strip(), "设置提醒间隔")
        self.assertIsNotNone(dialog.ok_button)
        self.assertIsNotNone(dialog.cancel_button)
        self.assertIsNotNone(dialog.error_label)
        self.assertIsNotNone(dialog.hours_input)
        self.assertIsNotNone(dialog.minutes_input)
        self.assertIsNotNone(dialog.seconds_input)
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertTrue(dialog.ok_button.minimumWidth() >= 110)
        self.assertTrue(dialog.cancel_button.minimumWidth() >= 110)
        self.assertFalse(dialog.hours_input.text() == "")
        self.assertFalse(dialog.minutes_input.text() == "")
        self.assertFalse(dialog.seconds_input.text() == "")
        self.assertEqual(dialog.layout().count(), 3)
        self.assertIsNotNone(dialog.layout().itemAt(0))
        self.assertIsNotNone(dialog.layout().itemAt(1))
        self.assertIsNotNone(dialog.layout().itemAt(2))
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.ok_button.objectName(), "primaryActionButton")
        self.assertEqual(dialog.cancel_button.objectName(), "secondaryActionButton")
        self.assertEqual(dialog.hours_input.objectName(), "settingsHoursInput")
        self.assertEqual(dialog.minutes_input.objectName(), "settingsMinutesInput")
        self.assertEqual(dialog.seconds_input.objectName(), "settingsSecondsInput")
        self.assertEqual(dialog.error_label.objectName(), "settingsErrorLabel")
        self.assertEqual(dialog.minimumWidth(), 360)
        self.assertIsNotNone(dialog.layout())
        self.assertIsNotNone(dialog.button_box)
        self.assertIsNotNone(dialog.ok_button)
        self.assertIsNotNone(dialog.cancel_button)
        self.assertEqual(dialog.layout().count(), 3)
        self.assertTrue(isinstance(dialog.hours_input.text(), str))
        self.assertTrue(isinstance(dialog.minutes_input.text(), str))
        self.assertTrue(isinstance(dialog.seconds_input.text(), str))
        self.assertTrue(dialog.ok_button.styleSheet())
        self.assertTrue(dialog.cancel_button.styleSheet())
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.result(), 0)
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.error_label.objectName(), "settingsErrorLabel")
        self.assertEqual(dialog.windowTitle(), "设置提醒间隔")
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.ok_button.text(), "保存")
        self.assertEqual(dialog.cancel_button.text(), "取消")
        self.assertEqual(dialog.minimumWidth(), 360)
        self.assertTrue(dialog.styleSheet())
        self.assertTrue(dialog.ok_button.styleSheet())
        self.assertTrue(dialog.cancel_button.styleSheet())
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.result(), 0)
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.hours_input.text(), "0")
        self.assertEqual(dialog.minutes_input.text(), "0")
        self.assertEqual(dialog.seconds_input.text(), "30")
        self.assertEqual(dialog.error_label.text(), "")
        self.assertFalse(dialog.try_accept() is None)
        self.assertEqual(dialog.get_interval_seconds(), 30)
        self.assertEqual(dialog.error_label.text(), "")
        self.assertEqual(dialog.result(), dialog.Accepted)

    def test_reminder_dialog_uses_named_widgets_for_polish(self):
        dialog = ReminderDialog()

        self.assertEqual(dialog.status_label.objectName(), "reminderStatusLabel")
        self.assertEqual(dialog.message_label.objectName(), "reminderMessageLabel")

    def test_settings_dialog_action_buttons_use_improved_width(self):
        dialog = SettingsDialog(interval_seconds=30)

        self.assertGreaterEqual(dialog.ok_button.minimumWidth(), 110)
        self.assertGreaterEqual(dialog.cancel_button.minimumWidth(), 110)
        self.assertEqual(dialog.ok_button.objectName(), "primaryActionButton")
        self.assertEqual(dialog.cancel_button.objectName(), "secondaryActionButton")

    def test_settings_dialog_buttons_apply_blue_styles_directly(self):
        dialog = SettingsDialog(interval_seconds=30)

        self.assertIn("background: #2563eb;", dialog.ok_button.styleSheet())
        self.assertIn("color: white;", dialog.ok_button.styleSheet())
        self.assertIn("background: #3b82f6;", dialog.cancel_button.styleSheet())
        self.assertIn("color: white;", dialog.cancel_button.styleSheet())
        self.assertEqual(dialog.ok_button.text(), "保存")
        self.assertEqual(dialog.cancel_button.text(), "取消")
        self.assertEqual(dialog.ok_button.objectName(), "primaryActionButton")
        self.assertEqual(dialog.cancel_button.objectName(), "secondaryActionButton")


if __name__ == "__main__":
    unittest.main()
